name: "Example:CI"

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: example

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: "yarn.lock"
          node-version-file: "../.tool-versions"
      - run: yarn install --frozen-lockfile
      - run: yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: "yarn.lock"
          node-version-file: "../.tool-versions"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
